### PR TITLE
Add iPhone 6S(Samsung), 10.3.1 to the symbols file

### PR DESCRIPTION
**Pull request by MrARM**
Personal device runs this, so I might as well add it from my own version!

### CODE REVIEW

**Comment by NickSB2013** [comment]
The iPhone 6s was manufactured using 2 different suppliers for the processors, Does it still require separate offsets for both processors (in previous jailbreaks, TSMC and Samsung processors required different offsets and TSMC offsets were overlooked/missing for a period of time.) if so, which chip do you have, so that we know which offsets are still needed. Thank you.

**Comment by MrARM** [comment]
This is the Samsung offsets.  I don't think I can change the commit message but that what it is. I'm going to work on the TSMC offsets later today.

**Comment by talanov** [comment]
@MrARM Please, close your PR. arx8x is on it (you can check out his fork via PR list).

**Comment by NickSB2013** [comment]
Sounds good MrARM, thank you!

**Pull request closed without merging**
